apiVersion: v2
name: qnap-display-control
version: "1.0.0"
appVersion: "1.0.0"
description: "QNAP Display Control with USB Copy Button Support for TrueNAS"
type: application
keywords:
  - qnap
  - display
  - hardware
  - usb
  - copy
  - led
home: https://github.com/robert-wenk/display
sources:
  - https://github.com/robert-wenk/display
maintainers:
  - name: Robert Wenk
    email: robert@example.com
annotations:
  truecharts.org/category: "hardware"
  truecharts.org/min_helm_version: "3.6"
  truecharts.org/max_helm_version: "3.99"
icon: https://www.qnap.com/i/_attach_file/product/photo/800_500/119_1605252979_TS-670%20Pro_02.png
